### ISSUE TITLE
Unable to run the app

### ISSUE THREAD

**Issue by mateuo777** [MyPureCloud/knowledge-connector-app#8]
Want to use genesys as source and destination.

GENESYS_SOURCE_LOGIN_URL=https://login.mypurecloud.de
GENESYS_SOURCE_BASE_URL=https://api.mypurecloud.de

GENESYS_LOGIN_URL=https://login.mypurecloud.de
GENESYS_BASE_URL=https://api.mypurecloud.de

I put this into .env file along with the client ID and secret and KB ID.

root@icxnbR90VW0T2:/home/mateusz/knowledge-connector-app# npm version
{
  'knowledge-connector-app': '0.2.0',
  npm: '9.6.7',
  node: '18.17.1',
  acorn: '8.8.2',
  ada: '2.5.0',
  ares: '1.19.1',
  brotli: '1.0.9',
  cldr: '43.0',
  icu: '73.1',
  llhttp: '6.0.11',
  modules: '108',
  napi: '9',
  nghttp2: '1.52.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.10+quic',
  simdutf: '3.2.12',
  tz: '2023c',
  undici: '5.22.1',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.18',
  v8: '10.2.154.26-node.26',
  zlib: '1.2.13.1-motley'
}

root@icxnbR90VW0T2:/home/mateusz/knowledge-connector-app# npm run build

> knowledge-connector-app@0.2.0 build
> tsc

root@icxnbR90VW0T2:/home/mateusz/knowledge-connector-app# npm start

> knowledge-connector-app@0.2.0 start
> node dist/index.js

{"level":"info","message":"Started"}
{"level":"info","message":"GenesysLoader task running"}
{"level":"info","message":"Fetching data..."}
{"level":"info","message":"Categories loaded: 0"}
{"level":"info","message":"Labels loaded: 0"}
{"level":"info","message":"Documents loaded: 0"}
{"level":"info","message":"GenesysLoader task finished"}
{"level":"info","message":"ImageProcessor task running"}
{"level":"info","message":"Images uploaded: 0"}
{"level":"info","message":"ImageProcessor task finished"}
{"level":"info","message":"PrefixExternalId task running"}
{"level":"error","message":"Error executing PrefixExternalId: Error: Missing EXTERNAL_ID_PREFIX from config"}
{"level":"error","message":"Connector app aborted. Missing EXTERNAL_ID_PREFIX from config","stack":"Error: Missing EXTERNAL_ID_PREFIX from config\n    at validateNonNull (file:///home/mateusz/knowledge-connector-app/dist/utils/validate-non-null.js:9:15)\n    at PrefixExternalId.run (file:///home/mateusz/knowledge-connector-app/dist/processor/prefix-external-id.js:13:9)\n    at file:///home/mateusz/knowledge-connector-app/dist/pipe/pipe.js:158:54\n    at wrapFunction (file:///home/mateusz/knowledge-connector-app/dist/utils/wrap-function.js:9:22)\n    at Pipe.execute (file:///home/mateusz/knowledge-connector-app/dist/pipe/pipe.js:158:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Pipe.executeProcessors (file:///home/mateusz/knowledge-connector-app/dist/pipe/pipe.js:137:31)\n    at async Pipe.start (file:///home/mateusz/knowledge-connector-app/dist/pipe/pipe.js:105:31)"}

What is the EXTERNAL_ID_PREFIX and why is it needed?

**Comment by mateuo777** [comment]
I made some changes the .env as the article IDs were same, so created an empty one on the target org:

CONFIGURER=genesys
GENESYS_SOURCE_LOGIN_URL=https://login.mypurecloud.de/
GENESYS_SOURCE_BASE_URL=https://api.mypurecloud.de/
GENESYS_SOURCE_CLIENT_ID=51f58acb-510e-4e5b-b55d-f8fdffe38b9d
GENESYS_SOURCE_CLIENT_SECRET=EAN_VPlCuo8vYn9WEQsFMNwtMyjaPL02MIiMAYw0U6k
GENESYS_SOURCE_KNOWLEDGE_BASE_ID=e29b8b79-95dc-49b5-af8a-fa2e61318530
 
GENESYS_LOGIN_URL=https://login.mypurecloud.de/
GENESYS_BASE_URL=https://api.mypurecloud.de/
GENESYS_CLIENT_ID=1222a3b9-806b-447d-bbe3-54e495bc6a34
GENESYS_CLIENT_SECRET=SNRTlIiXm0LoCCJk8Q66S9cgc2Ys7G4MjBChfQSNK0s
GENESYS_KNOWLEDGE_BASE_ID=69ad6b7f-dcbb-4ac5-be49-37baf7b80fc0

But still getting the same error.

**Comment by petergaras** [comment]
> I made some changes the .env as the article IDs were same, so created an empty one on the target org:
> 
> CONFIGURER=genesys GENESYS_SOURCE_LOGIN_URL=https://login.mypurecloud.de/ GENESYS_SOURCE_BASE_URL=https://api.mypurecloud.de/ GENESYS_SOURCE_CLIENT_ID= GENESYS_SOURCE_CLIENT_SECRET= GENESYS_SOURCE_KNOWLEDGE_BASE_ID=
> 
> GENESYS_LOGIN_URL=https://login.mypurecloud.de/ GENESYS_BASE_URL=https://api.mypurecloud.de/ GENESYS_CLIENT_ID= GENESYS_CLIENT_SECRET= GENESYS_KNOWLEDGE_BASE_ID=
> 
> But still getting the same error.

I've removed the secrets from your post. Please deactivate those OAuth clients ASAP.

**Comment by mateuo777** [comment]
Thank you. These tokens have been immediately deactivated. 
Will there be any documentation updates?

**Comment by petergaras** [comment]
> Thank you. These tokens have been immediately deactivated. Will there be any documentation updates?

Yes, I made this parameter optional:
https://github.com/MyPureCloud/knowledge-connector-app/pull/9
And also, I extended the wiki:
https://github.com/MyPureCloud/knowledge-connector-app/wiki/ExternalIdPrefix

**Comment by mateuo777** [comment]
It works after I added a dummy External Prefix like this:

EXTERNAL_ID_PREFIX=abcdefghij

Thanks.

Now I have a problem with articles that contain images.
I have one article which has an image taken from the response assets. 

When I start the app:

{"level":"info","message":"ImageProcessor task running"}
{"level":"error","message":"Error executing ImageProcessor: Error: Api request [https://api.mypurecloud.de/api/v2/responsemanagement/responseassets/search] failed with status [500] and message [{\"message\":\"The server encountered an unexpected condition which prevented it from fulfilling the request.\",\"code\":\"internal.server.error\",\"status\":500,\"contextId\":\"9c28d2de-cde2-4314-8e4c-b162501ec7be\",\"details\":[],\"errors\":[]}]"}
{"level":"error","message":"Connector app aborted. Api request [https://api.mypurecloud.de/api/v2/responsemanagement/responseassets/search] failed with status [500] and message [{\"message\":\"The server encountered an unexpected condition which prevented it from fulfilling the request.\",\"code\":\"internal.server.error\",\"status\":500,\"contextId\":\"9c28d2de-cde2-4314-8e4c-b162501ec7be\",\"details\":[],\"errors\":[]}]","stack":"Error: Api request [https://api.mypurecloud.de/api/v2/responsemanagement/responseassets/search] failed with status [500] and message [{\"message\":\"The server encountered an unexpected condition which prevented it from fulfilling the request.\",\"code\":\"internal.server.error\",\"status\":500,\"contextId\":\"9c28d2de-cde2-4314-8e4c-b162501ec7be\",\"details\":[],\"errors\":[]}]\n    at GenesysDestinationApi.verifyResponse (file:///home/mateusz/knowledge-connector-app/dist/genesys/genesys-api.js:70:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async GenesysDestinationApi.innerFetch (file:///home/mateusz/knowledge-connector-app/dist/genesys/genesys-api.js:63:9)\n    at async GenesysDestinationAdapter.lookupImage (file:///home/mateusz/knowledge-connector-app/dist/genesys/genesys-destination-adapter.js:28:26)\n    at async ImageProcessor.processImageBlock (file:///home/mateusz/knowledge-connector-app/dist/processor/image-processor.js:57:22)\n    at async ImageProcessor.processArticle (file:///home/mateusz/knowledge-connector-app/dist/processor/image-processor.js:38:13)\n    at async ImageProcessor.run (file:///home/mateusz/knowledge-connector-app/dist/processor/image-processor.js:25:17)\n    at async wrapFunction (file:///home/mateusz/knowledge-connector-app/dist/utils/wrap-function.js:9:16)\n    at async Pipe.execute (file:///home/mateusz/knowledge-connector-app/dist/pipe/pipe.js:158:24)\n    at async Pipe.executeProcessors (file:///home/mateusz/knowledge-connector-app/dist/pipe/pipe.js:137:31)"}

I have an image with absolute URL:

https://api-cdn.mypurecloud.de/response-assets/uploads/af343fd0-bc94-424a-b6e2-9c4b66de087f/ea64d85a-6d2a-40a1-81c3-38147f2e8cb9.ef0f7e69-0477-42ff-a98c-82b707568a9d

What should be defined as relative image URL here?

I tried different variations but neither of those worked.

**Comment by mateuo777** [comment]
I have now one article that contains an image.
The image I use is located in the response assets library. 
I define the variable like this:

RELATIVE_IMAGE_BASE_URL=/response-assets/v2/uploads/af343fd0-bc94-424a-b6e2-9c4b66de087f/b98322ab-bff5-48f4-a530-583fbe97d050.02edd437-ffc4-49c5-a666-fd2fd3ad8fb2.png

But it fails anyway:

{"level":"info","message":"ImageProcessor task running"}
{"level":"error","message":"Error executing ImageProcessor: Error: Api request [https://api.mypurecloud.de/api/v2/responsemanagement/responseassets/search] failed with status [500] and message [{\"message\":\"The server encountered an unexpected condition which prevented it from fulfilling the request.\",\"code\":\"internal.server.error\",\"status\":500,\"contextId\":\"76baec3a-c283-4664-937f-0894cddfd822\",\"details\":[],\"errors\":[]}]"}
{"level":"error","message":"Connector app aborted. Api request [https://api.mypurecloud.de/api/v2/responsemanagement/responseassets/search] failed with status [500] and message [{\"message\":\"The server encountered an unexpected condition which prevented it from fulfilling the request.\",\"code\":\"internal.server.error\",\"status\":500,\"contextId\":\"76baec3a-c283-4664-937f-0894cddfd822\",\"details\":[],\"errors\":[]}]","stack":"Error: Api request [https://api.mypurecloud.de/api/v2/responsemanagement/responseassets/search] failed with status [500] and message [{\"message\":\"The server encountered an unexpected condition which prevented it from fulfilling the request.\",\"code\":\"internal.server.error\",\"status\":500,\"contextId\":\"76baec3a-c283-4664-937f-0894cddfd822\",\"details\":[],\"errors\":[]}]\n    at GenesysDestinationApi.verifyResponse (file:///home/mateusz/knowledge-connector-app/dist/genesys/genesys-api.js:70:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async GenesysDestinationApi.innerFetch (file:///home/mateusz/knowledge-connector-app/dist/genesys/genesys-api.js:63:9)\n    at async GenesysDestinationAdapter.lookupImage (file:///home/mateusz/knowledge-connector-app/dist/genesys/genesys-destination-adapter.js:28:26)\n    at async ImageProcessor.processImageBlock (file:///home/mateusz/knowledge-connector-app/dist/processor/image-processor.js:57:22)\n    at async ImageProcessor.processArticle (file:///home/mateusz/knowledge-connector-app/dist/processor/image-processor.js:38:13)\n    at async ImageProcessor.run (file:///home/mateusz/knowledge-connector-app/dist/processor/image-processor.js:25:17)\n    at async wrapFunction (file:///home/mateusz/knowledge-connector-app/dist/utils/wrap-function.js:9:16)\n    at async Pipe.execute (file:///home/mateusz/knowledge-connector-app/dist/pipe/pipe.js:158:24)\n    at async Pipe.executeProcessors (file:///home/mateusz/knowledge-connector-app/dist/pipe/pipe.js:137:31)"}

It works if I remove the image from the article.
